apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: rok
spec:
  provider: azure
  secretObjects:
    - secretName: database-configs
      type: Opaque
      data:
        - objectName: SqlConnectionString
          key: SqlConnectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "KEYVAULTNAME"
    objects: |
      array:
        - |
          objectName: SqlConnectionString
          objectType: secret
          objectVersion: ""
    tenantID: "YOUR-TENANT-ID"