apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ntk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: sul-back
          image: meetupsul.azurecr.io/api:novalidate
          env:
            - name: DataOptions__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-configs
                  key: SqlConnectionString
            - name: AuthOptions__BaseUrl
              value: "http://4.225.37.67/"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
          nodePublishSecretRef:
            name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ntk
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: back